apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-ui
spec:
  replicas: {{ .Values.todoui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todo-ui
    spec:
      containers:
      - name: {{ .Release.Name }}-todo-ui
        image: {{ .Values.common.container_registry_url}}/{{.Values.todoui.image.name}}:{{ .Values.todoui.image.tag }}
        ports:
        - containerPort: {{ .Values.todoui.containerport }}
