apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-ui-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-ui-svc
  ports:
  - port: {{ .Values.todoui.serviceport }}
    targetPort: {{ .Values.todoui.containerport }}
