apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-add-task
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-add-task
  ports:
  - port: {{ .Values.addtask.serviceport }}
    targetPort: {{ .Values.addtask.containerport }}