apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-get-tasks
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-get-tasks
  ports:
    - port: {{ .Values.gettask.serviceport }}
      targetPort: {{ .Values.gettask.containerport }}
